sudo: required
services:
  - docker

before_install:
  - docker build -t joshnavru/travis-ci-heroku-aws-example .

script:
  - docker run joshnavru/travis-ci-heroku-aws-example yarn test

branches:
  only:
    - master
    - develop

deploy:
  provider: heroku:git
  api_key: $HEROKU_API_KEY
  edge: true
  app: travis-ci-heroku-aws-example
  on:
    branch: develop