sudo: required
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose run --rm api yarn test

branches:
  only:
    - master
    - develop
    - feature

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true
  app: travis-ci-heroku-aws-example
  on:
    branch: develop
