sudo: required
services:
  - docker
  - mongodb

before_install:
  - docker build -t joshnavru/example .

script:
  - docker run -e MONGODB_URL=$MONGODB_URL joshnavru/example yarn test

branches:
  only:
    - master
    - develop
    - feature

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true
  app: travis-ci-heroku-aws-example
  on:
    branch: develop
