sudo: required
services:
  - docker

# before_install:
#   - docker build -t joshnavru/travis-ci-heroku-aws-example .

script:
  - docker-compose run --rm api yarn test

branches:
  only:
    - master
    - develop

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true
  app: travis-ci-heroku-aws-example
  on:
    branch: develop
